export const leaders = [
  {
    name: "Chad Huff",
    title: "Chief Executive Officer",
    office: "Aberdeen",
    image: "/images/leadership/chad.jpg",
    bio: "With experience in the construction industry since 1992, Chad oversees all the daily general operations for the company both on and off-site. He offers vast knowledge and experience in construction from all perspectives — owner, architect and contractor.",
  },
  {
    name: "Cory Huff",
    title: "Chief Operating Officer",
    office: "Aberdeen",
    image: "/images/leadership/cory.jpg",
    bio: "Cory manages the construction activities of the company both on and off-site. He works directly with the customers, ensuring timely completion and satisfaction. He has been working in the construction industry since 1995.",
  },
  {
    name: "Scott Gillen",
    title: "Vice President, Concrete Division",
    office: "Aberdeen",
    image: "/images/leadership/scott.jpg",
    bio: "Scott manages all aspects of the Concrete Division for Huff Construction. Scott graduated from SDSU in 1999 with a Construction Management Degree and has been in the construction industry since 1995.",
  },
  {
    name: "Chris Brockhouse",
    title: "Steel Building Sales | Project Manager",
    office: "Aberdeen",
    image: "/images/leadership/chris.jpg",
    bio: "Chris brings 18 years of sales and marketing experience to Steel Buildings and project management at Huff. He understands farming operations firsthand and works directly with ag producers to plan, price, and deliver steel buildings built around how they run their operation. A strategic planner by nature, Chris helps clients think a project all the way through before the first beam goes up.",
  },
  {
    name: "Greg Zens",
    title: "Project Manager | Draftsman",
    office: "Aberdeen",
    image: "/images/leadership/greg.jpg",
    bio: "Greg works with the team to help estimate, bid and manage projects while offering in-house design abilities through drafting and modeling. He graduated in 2019 from South Dakota State University with a Bachelor of Fine Arts in Architecture and a minor in Construction Management.",
  },
  {
    name: "Matt Beaner",
    title: "Project Advisor",
    office: "Aberdeen",
    image: "/images/leadership/matt.jpg",
    bio: "Matt brings 23 years of experience working in the construction industry, with emphasis in every scale of public building. Matt’s background and thorough understanding of all phases of construction ensures design-marriage at every step, working closely with owners, design team, and staff.",
  },
  {
    name: "Mark Hanley",
    title: "Project Manager",
    office: "Aberdeen",
    image: "/images/leadership/mark.jpg",
    bio: "Mark joined Huff Construction after nine years as the Operations and Maintenance Manager at Aberdeen's airport, overseeing all construction that took place on the airfield. Mark's ability to effectively manage safety while keeping a project on schedule makes him a great addition to the team.",
  },
  {
    name: "Chris Fettig",
    title: "Project Manager",
    office: "Aberdeen",
    image: "/images/leadership/chrisf.jpg",
    bio: "Chris works with the team to estimate, bid, and manage projects, drawing from over two decades of hands-on experience in the field. A 2006 graduate of Central High School, he has been in construction for 22 years and joined Huff in 2019. Prior to his current role, he served as an on-site superintendent, bringing valuable field insight and leadership to every project he oversees.",
  },
  {
    name: "Rachel Rieger",
    title: "Finance & Administration Specialist",
    office: "Aberdeen",
    image: "/images/leadership/rachel.jpg",
    bio: "Rachel is responsible for overseeing office related duties, assisting project managers, and bookkeeping responsibilities. She received her Master's Degree from Northern State University in Business Administration and Leadership.",
  },
  {
    name: "Dani Lundy",
    title: "Finance & Administration Specialist",
    office: "Aberdeen",
    image: "/images/leadership/dani.jpg",
    bio: "Dani manages and oversees all accounting functions for Huff and brings 15 years of experience across construction, retail, hospitality, agriculture, and other industries. She is a graduate of Northern State University and has served in roles ranging from bookkeeper to CFO. Dani holds several professional credentials, including Certified Management Accountant, Enrolled Agent, and Certified in Strategic Competitive Analysis.",
  },
  {
    name: "Nicole Jark",
    title: "Finance & Administration Specialist",
    office: "Aberdeen",
    image: "/images/leadership/nicole.jpg",
    bio: "Nicole manages the day-to-day operations of Huff's Aberdeen headquarters, serving as the first point of contact for visitors and keeping the office running smoothly. She brings about three years of office management experience and a strong administrative background to the role.",
  },

  // SIOUX FALLS

  {
    name: "LeRoy Ask",
    title: "Vice President, Sioux Falls Division",
    office: "Sioux Falls",
    locationLead: true,
    image: "/images/leadership/leroy.jpg",
    bio: "LeRoy brings 28 years of experience in the construction industry including leadership and management. He attended South Dakota State University for Construction Management and will be leading our Sioux Falls division with a strong commitment to innovation and excellence in every project we undertake.",
  },
  {
    name: "Chris Biren",
    title: "Project Manager",
    office: "Sioux Falls",
    image: "/images/leadership/chrisb.jpg",
    bio: "Chris is a highly experienced project manager with 26 years of commercial construction expertise. He brings a wealth of knowledge and leadership to his role. He holds an associate degree in architectural engineering technology from Southeast Technical Institute. Based in Sioux Falls since 1994, Chris is deeply rooted in the local construction industry.",
  },
  {
    name: "Austin Huff",
    title: "Architect",
    office: "Sioux Falls",
    image: "/images/leadership/austin.jpg",
    bio: "Austin specializes in the integration of architecture, development planning, and construction. By collaborating with owners during the earliest stages of a project, he helps align vision, budget, schedule, and constructability to create successful outcomes.",
  },
  {
    name: "Megan Hardie",
    title: "HR Manager",
    office: "Sioux Falls",
    image: "/images/leadership/megan.jpg",
    bio: "Megan oversees the human resources department at Huff Construction, focusing on employee relations, recruitment, and fostering a strong company culture. With 25 years of management experience, she is passionate about supporting and developing the people who drive Huff Construction’s success. She is a graduate of the University of South Dakota. Go Yotes!",
  },
  {
    name: "Troy Lerud",
    title: "Superintendent",
    office: "Sioux Falls",
    image: "/images/leadership/troy.png",
    bio: "Troy is our experienced Site Superintendent with over 30 years in the industry and a background in construction management. He's a safety-conscious professional, boasting 30-hour OSHA training and prior experience as a Safety Director. A Sioux Falls native and Washington High School graduate, Troy's roots run deep in the community.",
  },
  {
    name: "Chase Tempel",
    title: "Site Superintendent",
    office: "Sioux Falls",
    image: "/images/leadership/chase.jpg",
    bio: "With 20 years of construction experience, including 8 years as a Site Superintendent, Chase Tempel brings a wealth of expertise and a results-driven approach. Known for his critical thinking and commitment to excellence, he ensures that every project is completed efficiently and to the highest standards. He has been an integral part of the Sioux Falls community, both professionally and personally, for the past decade, embodying our values of integrity and dedication on every job site.",
  },
  {
    name: "Michael Hay",
    title: "Marketing Director",
    office: "Sioux Falls",
    image: "/images/leadership/michael.jpg",
    bio: "Michael leads marketing across all three Huff offices and divisions. He brings more than 25 years in creative and marketing leadership, including years on the architecture and engineering side of the industry. Based in Sioux Falls, Michael also supports business development.",
  },

  // NORFOLK

  {
    name: "Chris Daniels",
    title: "Vice President, Norfolk Division",
    office: "Norfolk",
    locationLead: true,
    image: "/images/leadership/daniels.jpg",
    bio: "Chris comes with over 15 years of construction experience which includes extensive healthcare, K-12 education, higher education, retail, financial, and property development. He is a graduate of Iowa State University from the Construction Engineering Program in 2009.",
  },
  {
    name: "Courtney Vakoc",
    title: "Project Manager",
    office: "Norfolk",
    image: "/images/leadership/courtney.jpg",
    bio: "Courtney is a finance graduate from Southern New Hampshire University with a knack for navigating the world of construction. With over 5 years of construction experience, she's a reliable hand in project coordination and management.",
  },
  {
    name: "Shawn Severs",
    title: "Superintendent",
    office: "Norfolk",
    image: "/images/leadership/shawn.jpg",
    bio: "Tim is a seasoned superintendent with over 25 years of construction experience. His attention to detail is unmatched, from safety protocols to assembling fine details, he ensures a safe, high-quality project delivered on time and under budget.",
  },
  {
    name: "Tim Drumheller",
    title: "Site Superintendent",
    office: "Norfolk",
    image: "/images/leadership/tim.jpg",
    bio: "Shawn manages construction activities of Huff Construction both on and off the job site. He works directly with customers, ensuring timely completion and satisfaction. Shawn has over 20 years in the construction industry in the general construction and electrical trades.",
  },
  {
    name: "Eric Kavan",
    title: "Project Manager",
    office: "Norfolk",
    image: "/images/leadership/eric.jpg",
    bio: "Eric is a seasoned Project Manager with 8+ years in commercial construction. He brings strong coordination, clear communication, and a commitment to quality that keeps projects running smoothly from start to finish.",
  },
];